[package]
name = "build-entity"
version = "0.1.0"
authors = ["letusfly85 <letusfly95@gmail.com>"]

[dependencies]
diesel = { version = "1.1.1", features = ["mysql"] }
diesel_codegen = { version = "0.16.0", features = ["mysql"] }
dotenv = "0.9.0"
tera = "0.11"
